version: '3'

services:
  myservice:
    image: isurufernando/myservice:latest
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: local-mysql
